# Classification of Countries on the basis of ingridients used in their recipies

### Importing the required libraries

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

### Reading the dataset

In [2]:
df = pd.read_csv('D://recipes.csv')
df.head()

country almond angelica anise anise_seed apple apple_brandy apricot  \
0  Vietnamese     No       No    No         No    No           No      No   
1  Vietnamese     No       No    No         No    No           No      No   
2  Vietnamese     No       No    No         No    No           No      No   
3  Vietnamese     No       No    No         No    No           No      No   
4  Vietnamese     No       No    No         No    No           No      No   

  armagnac artemisia  ... whiskey white_bread white_wine  \
0       No        No  ...      No          No         No   
1       No        No  ...      No          No         No   
2       No        No  ...      No          No         No   
3       No        No  ...      No          No         No   
4       No        No  ...      No          No         No   

  whole_grain_wheat_flour wine wood yam yeast yogurt zucchini  
0                      No   No   No  No    No     No       No  
1                      No   No   No  No    No     No       No  
2                      No   No   No  No    No     No       No  
3                      No   No   No  No    No     No       No  
4                      No   No   No  No    No     No       No  

[5 rows x 384 columns]

In [3]:
df.tail()

country almond angelica anise anise_seed apple apple_brandy apricot  \
57686   Japan     No       No    No         No    No           No      No   
57687   Japan     No       No    No         No    No           No      No   
57688   Japan     No       No    No         No    No           No      No   
57689   Japan     No       No    No         No    No           No      No   
57690   Japan     No       No    No         No    No           No      No   

      armagnac artemisia  ... whiskey white_bread white_wine  \
57686       No        No  ...      No          No         No   
57687       No        No  ...      No          No         No   
57688       No        No  ...      No          No         No   
57689       No        No  ...      No          No         No   
57690       No        No  ...      No          No         No   

      whole_grain_wheat_flour wine wood yam yeast yogurt zucchini  
57686                      No   No   No  No    No     No       No  
57687                      No   No   No  No    No     No       No  
57688                      No   No   No  No    No     No       No  
57689                      No   No   No  No    No     No       No  
57690                      No   No   No  No    No     No       No  

[5 rows x 384 columns]

In [4]:
df.shape

(57691, 384)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57691 entries, 0 to 57690
Columns: 384 entries, country to zucchini
dtypes: object(384)
memory usage: 169.0+ MB


In [6]:
df.country.unique()

array(['Vietnamese', 'Indian', 'Spanish_Portuguese', 'Jewish', 'French',
       'Central_SouthAmerican', 'Cajun_Creole', 'Thai', 'Scandinavian',
       'Greek', 'American', 'African', 'MiddleEastern',
       'EasternEuropean_Russian', 'Italian', 'Irish', 'Mexican',
       'Chinese', 'German', 'Mediterranean', 'Japanese', 'Moroccan',
       'Southern_SoulFood', 'English_Scottish', 'Asian', 'Southwestern',
       'chinese', 'mexico', 'japanese', 'east_asian', 'asian', 'western',
       'korean', 'italian', 'Canada', 'Turkey', 'Caribbean', 'Bangladesh',
       'India', 'France', 'Italy', 'Israel', 'Korea', 'Iran',
       'Eastern-Europe', 'South-African', 'UK-and-Ireland', 'China',
       'Belgium', 'Germany', 'South-America', 'Spain', 'Netherlands',
       'Scandinavia', 'Philippines', 'Indonesia', 'East-African',
       'Vietnam', 'Thailand', 'Switzerland', 'West-African',
       'North-African', 'Pakistan', 'Portugal', 'Mexico', 'Lebanon',
       'Malaysia', 'Austria', 'Japan'], dtype=

In [7]:
new_name = {
    'chinese' : 'Chinese',
    'mexico' : 'Mexican',
    'japanese' : 'Japanese',
    'east_asian' : 'East_Asian',
    'asian' : 'Asian',
    'western' : 'Western',
    'korean' : 'Korean',
    'italian' : 'Italian',
    'Canada' : 'Canadian',
    'Turkey' : 'Turkish',
    'India' : 'Indian',
    'France' : 'French',
    'Italy' : 'Italian',
    'Korea' : 'Korean',
    'Iran' : 'Iranian',
    'Eastern-Europe' : 'Eastern-European',
    'China' : 'Chinese',
    'Germany' : 'German',
    'South-America' : 'South-American',
    'Spain' : 'Spanish',
    'Scandinavia' : 'Scandinavian',
    'Vietnam' : 'Vietnamese',
    'Thailand' : 'Thai',
    'Portugal' : 'Portuguese',
    'Mexico' : 'Mexican',
    'Japan' : 'Japanese',
}

df['country'] = df['country'].replace(new_name)

In [8]:
df.country.unique()

array(['Vietnamese', 'Indian', 'Spanish_Portuguese', 'Jewish', 'French',
       'Central_SouthAmerican', 'Cajun_Creole', 'Thai', 'Scandinavian',
       'Greek', 'American', 'African', 'MiddleEastern',
       'EasternEuropean_Russian', 'Italian', 'Irish', 'Mexican',
       'Chinese', 'German', 'Mediterranean', 'Japanese', 'Moroccan',
       'Southern_SoulFood', 'English_Scottish', 'Asian', 'Southwestern',
       'East_Asian', 'Western', 'Korean', 'Canadian', 'Turkish',
       'Caribbean', 'Bangladesh', 'Israel', 'Iranian', 'Eastern-European',
       'South-African', 'UK-and-Ireland', 'Belgium', 'South-American',
       'Spanish', 'Netherlands', 'Philippines', 'Indonesia',
       'East-African', 'Switzerland', 'West-African', 'North-African',
       'Pakistan', 'Portuguese', 'Lebanon', 'Malaysia', 'Austria'],
      dtype=object)

In [9]:
columns_names = df.columns.tolist()
print(columns_names)

['country', 'almond', 'angelica', 'anise', 'anise_seed', 'apple', 'apple_brandy', 'apricot', 'armagnac', 'artemisia', 'artichoke', 'asparagus', 'avocado', 'bacon', 'baked_potato', 'balm', 'banana', 'barley', 'bartlett_pear', 'basil', 'bay', 'bean', 'beech', 'beef', 'beef_broth', 'beef_liver', 'beer', 'beet', 'bell_pepper', 'bergamot', 'berry', 'bitter_orange', 'black_bean', 'black_currant', 'black_mustard_seed_oil', 'black_pepper', 'black_raspberry', 'black_sesame_seed', 'black_tea', 'blackberry', 'blackberry_brandy', 'blue_cheese', 'blueberry', 'bone_oil', 'bourbon_whiskey', 'brandy', 'brassica', 'bread', 'broccoli', 'brown_rice', 'brussels_sprout', 'buckwheat', 'butter', 'buttermilk', 'cabbage', 'cabernet_sauvignon_wine', 'cacao', 'camembert_cheese', 'cane_molasses', 'caraway', 'cardamom', 'carnation', 'carob', 'carrot', 'cashew', 'cassava', 'catfish', 'cauliflower', 'caviar', 'cayenne', 'celery', 'celery_oil', 'cereal', 'chamomile', 'champagne_wine', 'chayote', 'cheddar_cheese', 'ch

In [10]:
columns_to_convert = ['almond', 'angelica', 'anise', 'anise_seed', 'apple', 'apple_brandy', 'apricot', 'armagnac', 'artemisia', 'artichoke', 'asparagus', 'avocado', 'bacon', 'baked_potato', 'balm', 'banana', 'barley', 'bartlett_pear', 'basil', 'bay', 'bean', 'beech', 'beef', 'beef_broth', 'beef_liver', 'beer', 'beet', 'bell_pepper', 'bergamot', 'berry', 'bitter_orange', 'black_bean', 'black_currant', 'black_mustard_seed_oil', 'black_pepper', 'black_raspberry', 'black_sesame_seed', 'black_tea', 'blackberry', 'blackberry_brandy', 'blue_cheese', 'blueberry', 'bone_oil', 'bourbon_whiskey', 'brandy', 'brassica', 'bread', 'broccoli', 'brown_rice', 'brussels_sprout', 'buckwheat', 'butter', 'buttermilk', 'cabbage', 'cabernet_sauvignon_wine', 'cacao', 'camembert_cheese', 'cane_molasses', 'caraway', 'cardamom', 'carnation', 'carob', 'carrot', 'cashew', 'cassava', 'catfish', 'cauliflower', 'caviar', 'cayenne', 'celery', 'celery_oil', 'cereal', 'chamomile', 'champagne_wine', 'chayote', 'cheddar_cheese', 'cheese', 'cherry', 'cherry_brandy', 'chervil', 'chicken', 'chicken_broth', 'chicken_liver', 'chickpea', 'chicory', 'chinese_cabbage', 'chive', 'cider', 'cilantro', 'cinnamon', 'citrus', 'citrus_peel', 'clam', 'clove', 'cocoa', 'coconut', 'coconut_oil', 'cod', 'coffee', 'cognac', 'concord_grape', 'condiment', 'coriander', 'corn', 'corn_flake', 'corn_grit', 'cottage_cheese', 'crab', 'cranberry', 'cream', 'cream_cheese', 'cucumber', 'cumin', 'cured_pork', 'currant', 'date', 'dill', 'durian', 'eel', 'egg', 'egg_noodle', 'elderberry', 'emmental_cheese', 'endive', 'enokidake', 'fennel', 'fenugreek', 'feta_cheese', 'fig', 'fish', 'flower', 'frankfurter', 'fruit', 'galanga', 'gardenia', 'garlic', 'gelatin', 'geranium', 'gin', 'ginger', 'goat_cheese', 'grape', 'grape_brandy', 'grape_juice', 'grapefruit', 'green_bell_pepper', 'green_tea', 'gruyere_cheese', 'guava', 'haddock', 'ham', 'hazelnut', 'herring', 'holy_basil', 'honey', 'hop', 'horseradish', 'huckleberry', 'jamaican_rum', 'japanese_plum', 'jasmine', 'jasmine_tea', 'juniper_berry', 'kaffir_lime', 'kale', 'katsuobushi', 'kelp', 'kidney_bean', 'kiwi', 'kohlrabi', 'kumquat', 'lamb', 'lard', 'laurel', 'lavender', 'leaf', 'leek', 'lemon', 'lemon_juice', 'lemon_peel', 'lemongrass', 'lentil', 'lettuce', 'licorice', 'lilac_flower_oil', 'lima_bean', 'lime', 'lime_juice', 'lime_peel_oil', 'lingonberry', 'litchi', 'liver', 'lobster', 'long_pepper', 'lovage', 'macadamia_nut', 'macaroni', 'mace', 'mackerel', 'malt', 'mandarin', 'mandarin_peel', 'mango', 'maple_syrup', 'marjoram', 'mate', 'matsutake', 'meat', 'melon', 'milk', 'milk_fat', 'mint', 'mozzarella_cheese', 'mung_bean', 'munster_cheese', 'muscat_grape', 'mushroom', 'mussel', 'mustard', 'mutton', 'nectarine', 'nira', 'nut', 'nutmeg', 'oat', 'oatmeal', 'octopus', 'okra', 'olive', 'olive_oil', 'onion', 'orange', 'orange_flower', 'orange_juice', 'orange_peel', 'oregano', 'ouzo', 'oyster', 'palm', 'papaya', 'parmesan_cheese', 'parsley', 'parsnip', 'passion_fruit', 'pea', 'peach', 'peanut', 'peanut_butter', 'peanut_oil', 'pear', 'pear_brandy', 'pecan', 'pelargonium', 'pepper', 'peppermint', 'peppermint_oil', 'pimenta', 'pimento', 'pineapple', 'pistachio', 'plum', 'popcorn', 'porcini', 'pork', 'pork_liver', 'pork_sausage', 'port_wine', 'potato', 'potato_chip', 'prawn', 'prickly_pear', 'provolone_cheese', 'pumpkin', 'quince', 'radish', 'raisin', 'rapeseed', 'raspberry', 'raw_beef', 'red_algae', 'red_bean', 'red_kidney_bean', 'red_wine', 'rhubarb', 'rice', 'roasted_almond', 'roasted_beef', 'roasted_hazelnut', 'roasted_meat', 'roasted_nut', 'roasted_peanut', 'roasted_pecan', 'roasted_pork', 'roasted_sesame_seed', 'romano_cheese', 'root', 'roquefort_cheese', 'rose', 'rosemary', 'rum', 'rutabaga', 'rye_bread', 'rye_flour', 'saffron', 'sage', 'sake', 'salmon', 'salmon_roe', 'sassafras', 'sauerkraut', 'savory', 'scallion', 'scallop', 'sea_algae', 'seaweed', 'seed', 'sesame_oil', 'sesame_seed', 'shallot', 'sheep_cheese', 'shellfish', 'sherry', 'shiitake', 'shrimp', 'smoke', 'smoked_fish', 'smoked_salmon', 'smoked_sausage', 'sour_cherry', 'sour_milk', 'soy_sauce', 'soybean', 'soybean_oil', 'spearmint', 'squash', 'squid', 'star_anise', 'starch', 'strawberry', 'strawberry_jam', 'strawberry_juice', 'sturgeon_caviar', 'sumac', 'sunflower_oil', 'sweet_potato', 'swiss_cheese', 'tabasco_pepper', 'tamarind', 'tangerine', 'tarragon', 'tea', 'tequila', 'thai_pepper', 'thyme', 'tomato', 'tomato_juice', 'truffle', 'tuna', 'turkey', 'turmeric', 'turnip', 'vanilla', 'veal', 'vegetable', 'vegetable_oil', 'vinegar', 'violet', 'walnut', 'wasabi', 'watercress', 'watermelon', 'wheat', 'wheat_bread', 'whiskey', 'white_bread', 'white_wine', 'whole_grain_wheat_flour', 'wine', 'wood', 'yam', 'yeast', 'yogurt', 'zucchini']
mapping = {'Yes':1,'No':0}
for column in columns_to_convert:
    df[column] = df[column].map(mapping)

In [11]:
df.head()

country  almond  angelica  anise  anise_seed  apple  apple_brandy  \
0  Vietnamese       0         0      0           0      0             0   
1  Vietnamese       0         0      0           0      0             0   
2  Vietnamese       0         0      0           0      0             0   
3  Vietnamese       0         0      0           0      0             0   
4  Vietnamese       0         0      0           0      0             0   

   apricot  armagnac  artemisia  ...  whiskey  white_bread  white_wine  \
0        0         0          0  ...        0            0           0   
1        0         0          0  ...        0            0           0   
2        0         0          0  ...        0            0           0   
3        0         0          0  ...        0            0           0   
4        0         0          0  ...        0            0           0   

   whole_grain_wheat_flour  wine  wood  yam  yeast  yogurt  zucchini  
0                        0     0     0    0      0       0         0  
1                        0     0     0    0      0       0         0  
2                        0     0     0    0      0       0         0  
3                        0     0     0    0      0       0         0  
4                        0     0     0    0      0       0         0  

[5 rows x 384 columns]

In [12]:
df.describe(include='all')

country        almond      angelica         anise    anise_seed  \
count      57691  57691.000000  57691.000000  57691.000000  57691.000000   
unique        53           NaN           NaN           NaN           NaN   
top     American           NaN           NaN           NaN           NaN   
freq       40150           NaN           NaN           NaN           NaN   
mean         NaN      0.040370      0.000017      0.003883      0.001508   
std          NaN      0.196828      0.004163      0.062191      0.038804   
min          NaN      0.000000      0.000000      0.000000      0.000000   
25%          NaN      0.000000      0.000000      0.000000      0.000000   
50%          NaN      0.000000      0.000000      0.000000      0.000000   
75%          NaN      0.000000      0.000000      0.000000      0.000000   
max          NaN      1.000000      1.000000      1.000000      1.000000   

               apple  apple_brandy       apricot      armagnac     artemisia  \
count   57691.000000  57691.000000  57691.000000  57691.000000  57691.000000   
unique           NaN           NaN           NaN           NaN           NaN   
top              NaN           NaN           NaN           NaN           NaN   
freq             NaN           NaN           NaN           NaN           NaN   
mean        0.042173      0.000641      0.010851      0.000191      0.000225   
std         0.200985      0.025317      0.103602      0.013807      0.015010   
min         0.000000      0.000000      0.000000      0.000000      0.000000   
25%         0.000000      0.000000      0.000000      0.000000      0.000000   
50%         0.000000      0.000000      0.000000      0.000000      0.000000   
75%         0.000000      0.000000      0.000000      0.000000      0.000000   
max         1.000000      1.000000      1.000000      1.000000      1.000000   

        ...       whiskey   white_bread    white_wine  \
count   ...  57691.000000  57691.000000  57691.000000   
unique  ...           NaN           NaN           NaN   
top     ...           NaN           NaN           NaN   
freq    ...           NaN           NaN           NaN   
mean    ...      0.002583      0.006448      0.038342   
std     ...      0.050755      0.080042      0.192023   
min     ...      0.000000      0.000000      0.000000   
25%     ...      0.000000      0.000000      0.000000   
50%     ...      0.000000      0.000000      0.000000   
75%     ...      0.000000      0.000000      0.000000   
max     ...      1.000000      1.000000      1.000000   

        whole_grain_wheat_flour          wine          wood           yam  \
count              57691.000000  57691.000000  57691.000000  57691.000000   
unique                      NaN           NaN           NaN           NaN   
top                         NaN           NaN           NaN           NaN   
freq                        NaN           NaN           NaN           NaN   
mean                   0.012723      0.017784      0.000572      0.001491   
std                    0.112077      0.132168      0.023910      0.038581   
min                    0.000000      0.000000      0.000000      0.000000   
25%                    0.000000      0.000000      0.000000      0.000000   
50%                    0.000000      0.000000      0.000000      0.000000   
75%                    0.000000      0.000000      0.000000      0.000000   
max                    1.000000      1.000000      1.000000      1.000000   

               yeast        yogurt      zucchini  
count   57691.000000  57691.000000  57691.000000  
unique           NaN           NaN           NaN  
top              NaN           NaN           NaN  
freq             NaN           NaN           NaN  
mean        0.058969      0.018322      0.019188  
std         0.235569      0.134113      0.137188  
min         0.000000      0.000000      0.000000  
25%         0.000000      0.000000      0.000000  
50%         0.000000      0.000000      0.000000  
75%         0.0

In [13]:
df.isnull().sum()

country       0
almond        0
angelica      0
anise         0
anise_seed    0
             ..
wood          0
yam           0
yeast         0
yogurt        0
zucchini      0
Length: 384, dtype: int64

In [14]:
y = df['country']
y

0        Vietnamese
1        Vietnamese
2        Vietnamese
3        Vietnamese
4        Vietnamese
            ...    
57686      Japanese
57687      Japanese
57688      Japanese
57689      Japanese
57690      Japanese
Name: country, Length: 57691, dtype: object

In [15]:
y = y.map({'Vietnamese':0, 'Indian':1, 'Spanish_Portuguese':2, 'Jewish':3, 'French':4,
       'Central_SouthAmerican':5, 'Cajun_Creole':6, 'Thai':7, 'Scandinavian':8,
       'Greek':9, 'American':10, 'African':11, 'MiddleEastern':12,
       'EasternEuropean_Russian':13, 'Italian':14, 'Irish':15, 'Mexican':16,
       'Chinese':17, 'German':18, 'Mediterranean':19, 'Japanese':20, 'Moroccan':21,
       'Southern_SoulFood':22, 'English_Scottish':23, 'Asian':24, 'Southwestern':25,
       'East_Asian':26, 'Western':27, 'Korean':28, 'Canadian':29, 'Turkish':30,
       'Caribbean':31, 'Bangladesh':32, 'Israel':33, 'Iranian':34, 'Eastern-European':35,
       'South-African':36, 'UK-and-Ireland':37, 'Belgium':38, 'South-American':39,
       'Spanish':40, 'Netherlands':41, 'Philippines':42, 'Indonesia':43,
       'East-African':44, 'Switzerland':45, 'West-African':46, 'North-African':47,
       'Pakistan':48, 'Portuguese':49, 'Lebanon':50, 'Malaysia':51, 'Austria':51})
y.head()

0    0
1    0
2    0
3    0
4    0
Name: country, dtype: int64

In [16]:
df.drop('country',axis=1,inplace=True)
df.head()

almond  angelica  anise  anise_seed  apple  apple_brandy  apricot  \
0       0         0      0           0      0             0        0   
1       0         0      0           0      0             0        0   
2       0         0      0           0      0             0        0   
3       0         0      0           0      0             0        0   
4       0         0      0           0      0             0        0   

   armagnac  artemisia  artichoke  ...  whiskey  white_bread  white_wine  \
0         0          0          0  ...        0            0           0   
1         0          0          0  ...        0            0           0   
2         0          0          0  ...        0            0           0   
3         0          0          0  ...        0            0           0   
4         0          0          0  ...        0            0           0   

   whole_grain_wheat_flour  wine  wood  yam  yeast  yogurt  zucchini  
0                        0     0     0    0      0       0         0  
1                        0     0     0    0      0       0         0  
2                        0     0     0    0      0       0         0  
3                        0     0     0    0      0       0         0  
4                        0     0     0    0      0       0         0  

[5 rows x 383 columns]

In [17]:
x = df

In [18]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=4)

In [19]:
print("size of x_train :",x_train.size)
print("size of x_test :",x_test.size)
print("size of y_train :",y_train.size)
print("size of y_test :",y_test.size)

size of x_train : 17676216
size of x_test : 4419437
size of y_train : 46152
size of y_test : 11539


In [20]:
rfcls = RandomForestClassifier(n_estimators=50,criterion='gini',random_state=2)
rfcls.fit(x_train,y_train)

RandomForestClassifier(n_estimators=50, random_state=2)

In [21]:
y_pred_1 = rfcls.predict(x_test)
y_pred_1

array([10, 10, 10, ..., 10, 10, 10], dtype=int64)

In [22]:
print(confusion_matrix(y_test,y_pred_1))

[[ 1  0  0 ...  0  0  0]
 [ 0 45  0 ...  0  0  1]
 [ 0  1  2 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  2  0 ...  0  0  0]]


In [24]:
import warnings

In [25]:
warnings.filterwarnings('ignore')

In [26]:
print(classification_report(y_test,y_pred_1))

              precision    recall  f1-score   support

           0       0.10      0.04      0.06        25
           1       0.49      0.35      0.41       128
           2       0.11      0.03      0.05        59
           3       0.00      0.00      0.00        69
           4       0.25      0.06      0.09       247
           5       0.03      0.02      0.02        60
           6       0.00      0.00      0.00        23
           7       0.06      0.04      0.05        47
           8       0.25      0.05      0.08        44
           9       0.05      0.02      0.03        52
          10       0.78      0.94      0.85      8016
          11       0.00      0.00      0.00        17
          12       0.00      0.00      0.00        50
          13       0.00      0.00      0.00        25
          14       0.47      0.27      0.35       652
          15       0.25      0.07      0.11        15
          16       0.53      0.40      0.45       463
          17       0.05    

In [27]:
print(accuracy_score(y_test,y_pred_1))

0.7010139526822081


# Our model is 70% accurate